# Generated by Django 5.2.7 on 2025-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='color',
        ),
        migrations.AddField(
            model_name='home',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='homes.color'),
        ),
    ]
