# Generated by Django 5.2.7 on 2025-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='size',
        ),
        migrations.AddField(
            model_name='home',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='homes.size'),
        ),
    ]
