# Generated by Django 5.2.7 on 2025-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_color_remove_home_color_home_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
