# Generated by Django 5.2.7 on 2025-10-10 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_discount_alter_home_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='scu',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
